---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-application-set
  namespace: tenant-b-dev
spec:
  generators:
    - list:
        elements:
          - cluster: tenant-a-dev
            url: https://kubernetes.default.svc
            values:
              namespaceSuffix: "1"
  template:
    metadata:
      name: "guestbook-{{values.namespaceSuffix}}"
    spec:
      project: tenant-a-dev
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        name: "{{cluster}}"
        namespace: "guestbook-b-app-set-{{values.namespaceSuffix}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
