apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-b-app-of-apps-2
  namespace: tenant-b-dev
spec:
  project: tenant-b-dev
  source:
    repoURL: https://github.com/gabriel-brotas/tenant-b-app-of-apps-2
    targetRevision: HEAD
    path: dev
  destination:
    name: in-cluster
    namespace: tenant-b-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
